[package]
name = "rockscript"
version = "0.2.3"
edition = "2024"
description = "Esolang called Rockscript"
license = "MIT"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
directories = "6.0.0"
rockscript-core = { path = "../rockscript-core", version = "0.2.3" }
rustyline = { version = "18.0.1", features = ["derive"] }

[[bin]]
name = "rockscript"
path = "src/main.rs"
